### ISSUE TITLE
week 8 done

### ISSUE THREAD

**Issue by janaknpatel95** [janaknpatel95/HotelWebsite#11]
@pawaitemadisoncollege

week 8 done and there is screenshort in the git hub name week8.png that show test pass with getting place from zipcode.

**Comment by pawaitemadisoncollege** [comment]
This is a great start at implementing a restful api in your project @janaknpatel95.

As you continue working on this in the coming weeks, make sure you

- [x] use a property file for the web service url and your username https://github.com/janaknpatel95/HotelWebsite/blob/77519a523bd326cf6f6226ba1982a15cfba1c1d2/src/main/java/hotel/persistence/ApiDao.java#L18-L19
- [x] update the method to accept a zip code and country https://github.com/janaknpatel95/HotelWebsite/blob/77519a523bd326cf6f6226ba1982a15cfba1c1d2/src/main/java/hotel/persistence/ApiDao.java#L16, so that the values need to be hard-coded: https://github.com/janaknpatel95/HotelWebsite/blob/77519a523bd326cf6f6226ba1982a15cfba1c1d2/src/main/java/hotel/persistence/ApiDao.java#L18-L19
