### ISSUE TITLE
Week 4 activity

### ISSUE THREAD

**Issue by janaknpatel95** [janaknpatel95/HotelWebsite#2]
@pawaitemadisoncollege
i implement user database for my indi project so that i can use that for sign up and sing in with user. week four exercise it don please check

**Comment by pawaitemadisoncollege** [comment]
You have a nice start here with hibernate!

- [x] This method likely needs a transaction in order to work consistently (similar to your insert and delete methods). https://github.com/janaknpatel95/HotelWebsite/blob/2245b5b55634be372986fd673f68aaaf6bfa21da/src/main/java/hotel/persistence/UserDao.java#L27-L31
- [x] Add a unit test for the  saveOrUpdate method - you should be able to achieve 100% coverage of the UserDao.
- [ ] For future work: Verifying the entities are saved/updated/inserted correctly can be more thorough by implementing and using equals() on each entity - refer to the video Comparing Hibernate Entities with equals in week 5 for more detail.  An example of using that equals method in a unit test would be something like `assertTrue(expectedUser.equals(actualUser));` so that you don't have to compare each instance var/column manually like this: https://github.com/janaknpatel95/HotelWebsite/blob/2245b5b55634be372986fd673f68aaaf6bfa21da/src/test/java/hotel/persistence/UserDaoTest.java#L35.
