### ISSUE TITLE
Week5 

### ISSUE THREAD

**Issue by janaknpatel95** [janaknpatel95/HotelWebsite#4]
@pawaitemadisoncollege
week 5 done

**Comment by pawaitemadisoncollege** [comment]
Great job @janaknpatel95 It's good to see that you implemented the generic dao already!

- [x] remove the old daos (don't worry, you can still refer back to them in github if needed)
- [x] remember to update your time log at least every week
- [x] Be sure to implement and use equals() on each entity - refer to the video Comparing Hibernate Entities with equals in week 5 for more detail.  An example of using that equals method in a unit test would be something like `assertTrue(expectedUser.equals(actualUser));` so that you don't have to compare each instance var/column manually: https://github.com/janaknpatel95/HotelWebsite/blob/f6bd649059096b861dcc95b927014b89f8ce50a5/src/test/java/hotel/persistence/UserDaoTest.java#L51

**Comment by janaknpatel95** [comment]
fix all issue please check  @pawaitemadisoncollege

**Comment by pawaitemadisoncollege** [comment]
Good work on some of those changes.

- [ ] Assertions should not ever compare an object to itself. These aren't testing anything. 
https://github.com/janaknpatel95/HotelWebsite/blob/6cf5f0abb4800c4ab5bf4271c9881b00de1f5299/src/test/java/hotel/persistence/UserDaoTest.java#L52
and https://github.com/janaknpatel95/HotelWebsite/blob/6cf5f0abb4800c4ab5bf4271c9881b00de1f5299/src/test/java/hotel/persistence/UserDaoTest.java#L95
and https://github.com/janaknpatel95/HotelWebsite/blob/6cf5f0abb4800c4ab5bf4271c9881b00de1f5299/src/test/java/hotel/persistence/OrderTest.java#L49
and 
https://github.com/janaknpatel95/HotelWebsite/blob/6cf5f0abb4800c4ab5bf4271c9881b00de1f5299/src/test/java/hotel/persistence/OrderTest.java#L77-L78
