### ISSUE TITLE
CheckPoint 2

### ISSUE THREAD

**Issue by janaknpatel95** [janaknpatel95/HotelWebsite#9]
@pawaitemadisoncollege

i think i done with checkpoint 2 i created ERD for database and i been doing exercise in my project so i have full crud on data base. can you please let me know if im done or need more to do for check point 2?

**Comment by pawaitemadisoncollege** [comment]
You've been doing a nice job working regularly on your project and that's what checkpoint 2 is really about! Keep up that regular progress.

- [ ] Be sure to remove printlns and stacktraces with log statements. https://github.com/janaknpatel95/HotelWebsite/blob/596ab9896c79591985f31bda9c12cd3bc240c406/src/test/java/hotel/test/Database.java#L43-L48 and https://github.com/janaknpatel95/HotelWebsite/blob/596ab9896c79591985f31bda9c12cd3bc240c406/src/test/java/hotel/test/Database.java#L81, for example.
- [ ] Database design is looking good so far. In week 7 you will need to add a role table to get tomcat authentication/authorization work. Refer to my 9/30 post in slack #about the role table design
- [ ] Be careful with userids and passwords that might easily be found in github. Adding some of these types of files to .gitignore will help, but since git already IS tracking the file, there will be a bit of extra work to make git "forget" about it. https://stackoverflow.com/questions/1274057/how-to-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore
